#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export SVN_EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

export DE='gnome'
export TERM='xterm-256color'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-x4 -g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Less for psql!
if [ -e ~/.vim/bundle/vim-psql-pager/vimpsqlpager ]; then
  alias psql='PAGER=~/.vim/bundle/vim-psql-pager/vimpsqlpager psql';
  alias rpsql='PAGER=less /usr/bin/psql';
fi
if [ -e ~/.vim/bundle/vim-psql-pager/vimpgclipager ]; then
  alias pgcli='PAGER=~/.vim/bundle/vim-psql-pager/vimpgclipager pgcli';
  alias rpgcli='PAGER=less /usr/local/bin/pgcli';
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# Other Stuff
#
case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%n@%m: %~\a"}
        ;;
esac

export GOPATH="$HOME/workspace/golang"

# from /home/yokley/.bashrc
export EMAIL=kevin.yokley #youremailusername - for database scrubbing
export TEXTURA_APPDIR=$HOME/TexturaWD                # so that you don't have to tell tapp where your environment is
export TEXTURA_TTOOLS_VERBOSE=1                                  # display every command that dbmigration and tapp run along with its output
export TEXTURA_DATABASE_PATH=$HOME/appserver1 # where dumps are stored (defaults to home directory)
export TEXTURA_LETTUCE_VIRTUALENV_PATH=$HOME/virtualenvs/py27
export TEXTURA_MOCHA_VIRTUALENV_PATH=$HOME/virtualenvs/mocha
export T=https://dev1.texturallc.net/svn/textura
export PDQBACH_SETTINGS=~/pdqbach.conf
export PYPI='http://pypi.texturallc.net/cpm_dev/dev/+simple/'
dfpgdev2=(-h dfpgdev2.texturallc.net -U textura_system)
dfpgdev3=(-h dfpgdev3.texturallc.net -U kyokley)
dfappps1=(-h dfappps1.texturallc.net -U textura_system)
dev009=(-h dev009.texturallc.net -U yokley)
dev062=(-h dev062.texturallc.net -U kevinyokley)
kottke=10.140.6.48

almagest=(-h almagest.dyndns.org -U yokley)
export PATH=$PATH:~/.cabal/bin

alias google-chrome='google-chrome --disable-gpu-compositing'
alias runserver='./manage.py runserver --settings=dev_settings'
# and/or you can set the django settings module with an environment setting
# export DJANGO_SETTINGS_MODULE='dev_settings'
alias cpm='if [ $VIRTUAL_ENV ]; then deactivate; else source ~/virtualenvs/cpm/bin/activate; fi'
alias pdq='if [ $VIRTUAL_ENV ]; then deactivate; else source ~/virtualenvs/pdq/bin/activate; fi'
