#!/bin/bash
#
# Installation script which setup up an Ubuntu Precise machine to use this
# xmonad configuration.
#
# WARNING!!!
# * This has only been tested on a limited number of machines running
#   Ubuntu 12.04 64-bit.
# * This is not a sophisticated installation script by any stretch
#   of the imagination.
# * I take no responsibility if this overwrites any configuration settings
#   or otherwise messes up your system.
#
# Please review the readme file to find out exactly what it does and does not
# do. Or, visit the repository for more information:
# https://github.com/davidbrewer/xmonad-ubuntu-conf
#
# Author: David Brewer

echo "Installing required packages..."
sudo aptitude install -y cabal-install libxrandr-dev libghc-x11-xft-dev libxpm-dev ghc xbacklight
cabal update
cabal install xmonad --reinstall
cabal install xmonad-contrib --reinstall
sudo aptitude install xmobar
sudo aptitude install -y xcompmgr nitrogen trayer thunar terminator xautolock suckless-tools weather-util arandr moreutils
sudo pip install git+https://github.com/kyokley/gcalcli.git --force --upgrade
sudo pip install colorclass

echo "Creating xmonad xsession configuration..."
sudo mv /usr/share/xsessions/xmonad.desktop /usr/share/xsessions/xmonad.desktop.original
sudo cp ~/.xmonad/xmonad.desktop /usr/share/xsessions
sudo cp ~/.xmonad/images/custom_xmonad_badge.png /usr/share/unity-greeter

ln -s ~/.xmonad/wallpaper.jpg ~/Pictures/
ln -s ~/.xmonad/haters.jpg ~/Pictures/

# TODO: Run nitrogen and set the path to the pictures folder:
#     nitrogen ~/Pictures
# Add cabal to the path in .bashrc:
#     export PATH=$PATH:~/.cabal/bin

#It might be necessary to run
    #cabal install X11 -v --reinstall
#if
    #ghc -e Graphics.X11.Xinerama.compiledWithXinerama
#fails

echo "Don't forget to git clone git@github.com:kyokley/SpotifyController.git for spotify controls!"

gcalcli agenda > /dev/null
